---
- name: Ensure unzip is installed
  package:
    name: unzip
    state: present

- name: Verify packer is not installed
  package:
    name: packer
    state: absent

- name: Download Packer
  unarchive:
    src: "{{ packer_download_url }}"
    dest: "{{ packer_bin_path }}"
    remote_src: true
